"""Atomic, containment-checked writes for generated project folders.

Since Phase 10.3 this module is a thin, backend-agnostic facade: text
normalization (UTF-8, hard ``\\n`` endings, so generated bytes are identical on
every OS) lives here, while the actual storage primitives are delegated to the
active backend (`app.storage.get_storage()`). The default backend is the local
filesystem, whose behavior — same-directory temp file, flush + fsync +
``os.replace``, path-safety validation — is unchanged. Callers are untouched.
"""
from __future__ import annotations

import json
from typing import Optional

from app.storage import get_storage


def write_bytes(root: str, relative_path: str, data: bytes) -> str:
    """Atomically write `data` to `relative_path` under `root`."""
    return get_storage().write_bytes(root, relative_path, data)


def write_text(root: str, relative_path: str, text: str) -> str:
    """Atomically write `text` (UTF-8, `\\n` endings) to `relative_path`."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    return write_bytes(root, relative_path, normalized.encode("utf-8"))


def write_text_if_changed(root: str, relative_path: str, text: str) -> bool:
    """Write only if the stored bytes differ. Returns True if it wrote."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    data = normalized.encode("utf-8")
    existing = read_bytes(root, relative_path)
    if existing == data:
        return False
    write_bytes(root, relative_path, data)
    return True


def read_bytes(root: str, relative_path: str) -> Optional[bytes]:
    """Read raw bytes via the active backend. None if the object does not exist."""
    return get_storage().read_bytes(root, relative_path)


def read_text(root: str, relative_path: str) -> Optional[str]:
    """Read UTF-8 text via the active backend. None if the object does not exist."""
    data = read_bytes(root, relative_path)
    return None if data is None else data.decode("utf-8")


def ensure_file(root: str, relative_path: str) -> str:
    """Ensure an (empty) object exists without truncating an existing one."""
    return get_storage().ensure_file(root, relative_path)


def append_jsonl(root: str, relative_path: str, obj: dict) -> str:
    """Append one JSON object as a line to an append-only log."""
    line = json.dumps(obj, sort_keys=True, ensure_ascii=False) + "\n"
    return get_storage().append_line(root, relative_path, line)
