"""Atomic, containment-checked file writes for generated project folders.

Writes go to a same-directory temporary file which is flushed, fsync'd, and then
`os.replace`d onto the destination — a partial or crashed write never leaves a
half-written canonical file. Text is encoded UTF-8 with hard `\\n` line endings
(no platform translation), so generated bytes are identical on every OS.
"""
from __future__ import annotations

import json
import os
import tempfile
from typing import Optional

from app.fsmemory.path_safety import (
    PathSafetyError,
    is_reparse_point,
    resolve_within,
    safe_makedirs,
)


def _ensure_parent(root: str, relative_path: str) -> str:
    rel_dir = os.path.dirname(relative_path.replace("\\", "/"))
    if rel_dir:
        safe_makedirs(root, rel_dir)
    # Re-validate the full target immediately before the caller opens it.
    target = resolve_within(root, relative_path)
    parent = os.path.dirname(target)
    if is_reparse_point(parent):
        raise PathSafetyError(f"parent directory is a reparse point: {parent!r}")
    return target


def write_bytes(root: str, relative_path: str, data: bytes) -> str:
    """Atomically write `data` to `relative_path` under `root`. Returns abs path."""
    target = _ensure_parent(root, relative_path)
    parent = os.path.dirname(target)
    fd, tmp_path = tempfile.mkstemp(dir=parent, prefix=".tmp-", suffix=".part")
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(data)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_path, target)
        return target
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def write_text(root: str, relative_path: str, text: str) -> str:
    """Atomically write `text` (UTF-8, `\\n` endings) to `relative_path`."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    return write_bytes(root, relative_path, normalized.encode("utf-8"))


def write_text_if_changed(root: str, relative_path: str, text: str) -> bool:
    """Write only if the on-disk bytes differ. Returns True if it wrote."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    data = normalized.encode("utf-8")
    existing = read_bytes(root, relative_path)
    if existing == data:
        return False
    write_bytes(root, relative_path, data)
    return True


def read_bytes(root: str, relative_path: str) -> Optional[bytes]:
    """Read raw bytes via the safety layer. None if the file does not exist."""
    target = resolve_within(root, relative_path)
    try:
        with open(target, "rb") as fh:
            return fh.read()
    except (FileNotFoundError, IsADirectoryError):
        return None


def read_text(root: str, relative_path: str) -> Optional[str]:
    """Read UTF-8 text via the safety layer. None if the file does not exist."""
    data = read_bytes(root, relative_path)
    return None if data is None else data.decode("utf-8")


def ensure_file(root: str, relative_path: str) -> str:
    """Ensure an (empty) file exists without truncating an existing one."""
    target = _ensure_parent(root, relative_path)
    if not os.path.exists(target):
        write_bytes(root, relative_path, b"")
    return target


def append_jsonl(root: str, relative_path: str, obj: dict) -> str:
    """Append one JSON object as a line to an append-only log file."""
    target = _ensure_parent(root, relative_path)
    line = json.dumps(obj, sort_keys=True, ensure_ascii=False) + "\n"
    with open(target, "a", encoding="utf-8", newline="\n") as fh:
        fh.write(line)
    return target
