"""Deterministic Markdown renderers for the `context/*` pack.

Each renderer is a pure function of a `RenderContext` (project + workspace +
a single content-derived `updated_at`). Output is byte-stable: fixed key order
in front matter, stable headings, sorted collections, no wall-clock timestamps
in the body. This is what makes regeneration idempotent and golden-testable.

The four data-dependent files (ROADMAP, TASKS, DECISIONS, RISKS) render as
clearly-labelled placeholders until the Phase-4 planning entities exist.
"""
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from app.fsmemory.spec import ContextFileSpec
from app.models.project import Project
from app.models.workspace import Workspace


@dataclass(frozen=True)
class RenderContext:
    project: Project
    workspace: Workspace
    # Content-derived timestamp (max of source-entity updated_at). NOT wall-clock,
    # so two regenerations with unchanged data produce identical bytes.
    updated_at: str


def _wrap(kind: str, ctx: RenderContext, body: list[str]) -> str:
    front = [
        "---",
        f"project: {ctx.project.slug}",
        f"kind: {kind}",
        f"updated_at: {ctx.updated_at}",
        "source_of_truth: AgentBoard",
        "generated: true",
        "pinned: false",
        "---",
    ]
    return "\n".join(front + [""] + body) + "\n"


def _or(value: object, fallback: str) -> str:
    text = "" if value is None else str(value).strip()
    return text if text else fallback


# --- summary layer --------------------------------------------------------


def _project_body(ctx: RenderContext) -> list[str]:
    p, ws = ctx.project, ctx.workspace
    return [
        f"# {p.title}",
        "",
        _or(p.summary, "_No summary set._"),
        "",
        "## Identity",
        f"- Project ID: {p.id}",
        f"- Slug: {p.slug}",
        f"- Type: {_or(p.project_type, 'unset')}",
        f"- Status: {p.status}",
        f"- Workspace: {ws.name} ({ws.id})",
        "",
        "## Key links",
        f"- Folder root: {_or(p.folder_path, 'unset')}",
        "",
        "## Source",
        "Generated by AgentBoard from the project database. Edit project fields in",
        "the app, not here.",
    ]


def _context_body(ctx: RenderContext) -> list[str]:
    p = ctx.project
    return [
        "# Read me first",
        "",
        "## What & why",
        _or(p.summary, "_No summary set._"),
        "",
        "## Current focus",
        f"- Status: {p.status}",
        "- Live snapshot: [STATUS.md](STATUS.md)",
        "",
        "## Constraints",
        "- Governance: [AGENT_RULES.md](AGENT_RULES.md)",
        "- Allowed paths: [FILES_ALLOWED.md](FILES_ALLOWED.md)",
        "- Forbidden paths: [FILES_FORBIDDEN.md](FILES_FORBIDDEN.md)",
        "",
        "## Pointers",
        "- Architecture: [ARCHITECTURE.md](ARCHITECTURE.md)",
        "- Next step: [NEXT_STEP.md](NEXT_STEP.md)",
        "- Roadmap: [ROADMAP.md](ROADMAP.md)",
        "- Tasks: [TASKS.md](TASKS.md)",
    ]


def _status_body(ctx: RenderContext) -> list[str]:
    p = ctx.project
    return [
        "# Current status",
        "",
        "- Health: unknown",
        f"- Status: {p.status}",
        "- Active phase: phase tracking arrives in Phase 4",
        "- Open blockers: none tracked yet",
        f"- Last data change: {p.updated_at}",
    ]


def _next_step_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Current objective",
        "",
        "_No next-step objective has been set for this project yet._",
        "",
        "# Required reads",
        "- [CONTEXT.md](CONTEXT.md)",
        "- [AGENT_RULES.md](AGENT_RULES.md)",
        "",
        "# Constraints",
        "- Stay within [FILES_ALLOWED.md](FILES_ALLOWED.md); never touch"
        " [FILES_FORBIDDEN.md](FILES_FORBIDDEN.md).",
        "",
        "# Acceptance criteria",
        "- Defined per task.",
    ]


# --- data-dependent placeholders (populated in Phase 4) -------------------


def _placeholder(title: str, entity: str, sections: list[tuple[str, str]]) -> list[str]:
    lines = [
        f"# {title}",
        "",
        f"> _Placeholder._ This file is populated in Phase 4, when the {entity}",
        "> entity exists. It is generated now with a stable shape so agents can",
        "> rely on it being present.",
    ]
    for heading, body in sections:
        lines += ["", f"## {heading}", body]
    return lines


def _roadmap_body(_ctx: RenderContext) -> list[str]:
    return _placeholder(
        "Roadmap",
        "Phase/Stage/Milestone",
        [("Phases", "_None yet._"), ("Milestones", "_None yet._")],
    )


def _tasks_body(_ctx: RenderContext) -> list[str]:
    return _placeholder(
        "Tasks",
        "Task",
        [("Active", "_None yet._"), ("Done", "0 completed.")],
    )


def _decisions_body(_ctx: RenderContext) -> list[str]:
    return _placeholder(
        "Decisions",
        "Decision",
        [("Decision log", "_No decisions recorded yet._")],
    )


def _risks_body(_ctx: RenderContext) -> list[str]:
    return _placeholder(
        "Risks",
        "Risk",
        [("Open risks", "_None yet._"), ("Closed risks", "_None yet._")],
    )


# --- operational layer ----------------------------------------------------


def _agents_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Agent rules (cross-tool alias)",
        "",
        "Cross-tool alias of [AGENT_RULES.md](AGENT_RULES.md). Codex, Cursor, and",
        "OpenCode read this file; the canonical rules live in AGENT_RULES.md.",
        "",
        "See [AGENT_RULES.md](AGENT_RULES.md).",
    ]


def _agent_rules_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Agent rules",
        "",
        "## Scope",
        "- Operate only within [FILES_ALLOWED.md](FILES_ALLOWED.md).",
        "- Never read, modify, or exfiltrate paths in"
        " [FILES_FORBIDDEN.md](FILES_FORBIDDEN.md).",
        "",
        "## Approval",
        "- Every write proposed through an external AI surface is approval-gated"
        " (proposal -> human approve -> apply).",
        "- Local human actions may write directly; they are still validated and"
        " audited.",
        "",
        "## Response format",
        "1. What changed",
        "2. Files touched",
        "3. Validation performed",
        "4. Risks / open questions",
        "5. Exact next step",
    ]


def _files_allowed_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Allowed paths",
        "",
        "Glob allow-list of paths agents may read or modify for this project.",
        "Forbidden paths always win over allowed.",
        "",
        "- (none configured yet)",
    ]


def _files_forbidden_body(_ctx: RenderContext) -> list[str]:
    globs = sorted(
        [
            ".env",
            ".env.*",
            "**/.env",
            "**/.env.*",
            "secrets/**",
            "**/secrets/**",
            "credentials/**",
            "**/*credential*",
            "**/*.pem",
            "**/*.key",
        ]
    )
    return [
        "# Forbidden paths",
        "",
        "Glob deny-list of paths agents must never read, modify, or exfiltrate.",
        "These win over any allow rule and are never removed once added.",
        "",
        *[f"- {g}" for g in globs],
    ]


def _architecture_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Architecture",
        "",
        "## Stack",
        "_Not yet documented._",
        "",
        "## Module map",
        "_Not yet documented._",
        "",
        "## Key constraints",
        "- See [AGENT_RULES.md](AGENT_RULES.md).",
        "- Depth lives under `docs/`, not inlined here.",
    ]


def _test_plan_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Test plan",
        "",
        '## What "verified" means',
        "_Not yet documented for this project._",
        "",
        "## Commands",
        "- (none configured yet)",
        "",
        "## Smoke steps",
        "- (none configured yet)",
    ]


def _prompts_body(_ctx: RenderContext) -> list[str]:
    families = sorted(["claude", "codex", "chatgpt", "opencode", "cursor", "shared"])
    return [
        "# Prompts",
        "",
        "Index of ready-to-paste prompt templates. The prompts live in files under",
        "`prompts/<agent>/`, not inlined here.",
        "",
        *[f"- prompts/{family}/" for family in families],
    ]


def _changelog_body(ctx: RenderContext) -> list[str]:
    # Date derives from project.created_at (stable), never wall-clock.
    created_date = ctx.project.created_at[:10]
    return [
        "# Changelog",
        "",
        "Reverse-chronological, human-readable change history.",
        "",
        f"- {created_date}: Project folder initialised by AgentBoard.",
    ]


BODY_RENDERERS: dict[str, Callable[[RenderContext], list[str]]] = {
    "PROJECT.md": _project_body,
    "CONTEXT.md": _context_body,
    "STATUS.md": _status_body,
    "NEXT_STEP.md": _next_step_body,
    "ROADMAP.md": _roadmap_body,
    "TASKS.md": _tasks_body,
    "DECISIONS.md": _decisions_body,
    "RISKS.md": _risks_body,
    "AGENTS.md": _agents_body,
    "AGENT_RULES.md": _agent_rules_body,
    "FILES_ALLOWED.md": _files_allowed_body,
    "FILES_FORBIDDEN.md": _files_forbidden_body,
    "ARCHITECTURE.md": _architecture_body,
    "TEST_PLAN.md": _test_plan_body,
    "PROMPTS.md": _prompts_body,
    "CHANGELOG.md": _changelog_body,
}


def render(spec: ContextFileSpec, ctx: RenderContext) -> str:
    """Render the full file text (front matter + body) for one spec."""
    body = BODY_RENDERERS[spec.filename](ctx)
    return _wrap(spec.kind, ctx, body)
