"""Deterministic Markdown renderers for the `context/*` pack.

Each renderer is a pure function of a `RenderContext` (project + workspace +
a single content-derived `updated_at` + optional planning entity collections).
Output is byte-stable: fixed key order in front matter, stable headings, sorted
collections, no wall-clock timestamps in the body. This is what makes
regeneration idempotent and golden-testable.

Phase 4: ROADMAP, TASKS, DECISIONS, and RISKS are data-driven. All other files
remain project/workspace-derived. Empty collections produce stable "none yet"
output so golden tests still pass without seeded data.
"""
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field

from app.fsmemory.spec import ContextFileSpec
from app.mcp.serializers import redact
from app.models.project import Project
from app.models.workspace import Workspace
from app.prompt.boundary import defang

_CLOSED_RISK_STATUSES = frozenset({"mitigated", "accepted", "closed"})
_DONE_TASK_STATUSES = frozenset({"done", "canceled"})
_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


@dataclass(frozen=True)
class RenderContext:
    project: Project
    workspace: Workspace
    # Content-derived timestamp (max of source-entity updated_at). NOT wall-clock,
    # so two regenerations with unchanged data produce identical bytes.
    updated_at: str
    # Planning entity collections — empty by default so existing call sites
    # (context_service, golden tests) work without modification.
    phases: tuple = field(default_factory=tuple)
    stages: tuple = field(default_factory=tuple)
    tasks: tuple = field(default_factory=tuple)
    decisions: tuple = field(default_factory=tuple)
    risks: tuple = field(default_factory=tuple)
    blockers: tuple = field(default_factory=tuple)
    milestones: tuple = field(default_factory=tuple)


def _wrap(kind: str, ctx: RenderContext, body: list[str]) -> str:
    front = [
        "---",
        f"project: {ctx.project.slug}",
        f"kind: {kind}",
        f"updated_at: {ctx.updated_at}",
        "source_of_truth: Planarus",
        "generated: true",
        "pinned: false",
        "---",
    ]
    return "\n".join(front + [""] + body) + "\n"


def _sanitize(value: object) -> str:
    """Free-text DB fields are untrusted (agents read these files unwrapped):
    mask secret shapes first (redact-before-clip), then defang injection markers.
    Both passes are deterministic, so output stays byte-stable/golden-testable;
    benign text passes through unchanged."""
    text = "" if value is None else str(value).strip()
    if not text:
        return ""
    masked, _ = redact(text)
    return defang(masked)


def _or(value: object, fallback: str) -> str:
    text = _sanitize(value)
    return text if text else fallback


def _trunc(text: str, limit: int = 80) -> str:
    text = _sanitize(text)
    return text if len(text) <= limit else text[: limit - 1] + "…"


# --- summary layer --------------------------------------------------------


def _project_body(ctx: RenderContext) -> list[str]:
    p, ws = ctx.project, ctx.workspace
    return [
        f"# {_sanitize(p.title)}",
        "",
        _or(p.summary, "_No summary set._"),
        "",
        "## Identity",
        f"- Project ID: {p.id}",
        f"- Slug: {p.slug}",
        f"- Type: {_or(p.project_type, 'unset')}",
        f"- Status: {p.status}",
        f"- Workspace: {_sanitize(ws.name)} ({ws.id})",
        "",
        "## Key links",
        f"- Folder root: {_or(p.folder_path, 'unset')}",
        "",
        "## Source",
        "Generated by Planarus from the project database. Edit project fields in",
        "the app, not here.",
    ]


def _context_body(ctx: RenderContext) -> list[str]:
    p = ctx.project
    return [
        "# Read me first",
        "",
        "## What & why",
        _or(p.summary, "_No summary set._"),
        "",
        "## Current focus",
        f"- Status: {p.status}",
        "- Live snapshot: [STATUS.md](STATUS.md)",
        "",
        "## Constraints",
        "- Governance: [AGENT_RULES.md](AGENT_RULES.md)",
        "- Allowed paths: [FILES_ALLOWED.md](FILES_ALLOWED.md)",
        "- Forbidden paths: [FILES_FORBIDDEN.md](FILES_FORBIDDEN.md)",
        "",
        "## Pointers",
        "- Architecture: [ARCHITECTURE.md](ARCHITECTURE.md)",
        "- Next step: [NEXT_STEP.md](NEXT_STEP.md)",
        "- Roadmap: [ROADMAP.md](ROADMAP.md)",
        "- Tasks: [TASKS.md](TASKS.md)",
    ]


def _status_body(ctx: RenderContext) -> list[str]:
    p = ctx.project
    active_phase = next((ph for ph in ctx.phases if ph.status == "active"), None)
    active_phase_text = _sanitize(active_phase.title) if active_phase is not None else "none"
    open_blockers = [b for b in ctx.blockers if b.status == "open"]
    return [
        "# Current status",
        "",
        "- Health: unknown",
        f"- Status: {p.status}",
        f"- Active phase: {active_phase_text}",
        f"- Open blockers: {len(open_blockers)}",
        f"- Last data change: {p.updated_at}",
    ]


def _next_step_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Current objective",
        "",
        "_No next-step objective has been set for this project yet._",
        "",
        "# Required reads",
        "- [CONTEXT.md](CONTEXT.md)",
        "- [AGENT_RULES.md](AGENT_RULES.md)",
        "",
        "# Constraints",
        "- Stay within [FILES_ALLOWED.md](FILES_ALLOWED.md); never touch"
        " [FILES_FORBIDDEN.md](FILES_FORBIDDEN.md).",
        "",
        "# Acceptance criteria",
        "- Defined per task.",
    ]


# --- data-driven renderers (Phase 4) --------------------------------------


def _roadmap_body(ctx: RenderContext) -> list[str]:
    phases = sorted(ctx.phases, key=lambda p: (p.sort_order, p.id))
    stages = sorted(ctx.stages, key=lambda s: (s.sort_order, s.id))

    lines: list[str] = ["# Roadmap", ""]

    # Phases table
    lines.append("## Phases")
    if not phases:
        lines.append("_No phases yet._")
    else:
        lines += [
            "| # | Title | Status |",
            "|---|---|---|",
        ]
        for i, ph in enumerate(phases, 1):
            lines.append(f"| {i} | {_sanitize(ph.title)} | {ph.status} |")

    lines.append("")

    # Stages table
    lines.append("## Stages")
    if not stages:
        lines.append("_No stages yet._")
    else:
        phase_title: dict[str, str] = {ph.id: _sanitize(ph.title) for ph in phases}
        lines += [
            "| Phase | Title | Status |",
            "|---|---|---|",
        ]
        for stg in stages:
            ph_name = phase_title.get(stg.phase_id, stg.phase_id)
            lines.append(f"| {ph_name} | {_sanitize(stg.title)} | {stg.status} |")

    # Milestones — soonest target_date first, undated last; then sort_order.
    milestones = sorted(
        ctx.milestones,
        key=lambda m: (m.target_date or "9999-99-99", m.sort_order, m.id),
    )
    lines += ["", "## Milestones"]
    if not milestones:
        lines.append("_None yet._")
    else:
        lines += [
            "| Target | Title | Status |",
            "|---|---|---|",
        ]
        for m in milestones:
            target = _sanitize(m.target_date) or "—"
            lines.append(f"| {target} | {_trunc(m.title, 50)} | {m.status} |")
    return lines


def _tasks_body(ctx: RenderContext) -> list[str]:
    active = sorted(
        [t for t in ctx.tasks if t.status not in _DONE_TASK_STATUSES],
        key=lambda t: (t.sort_order, t.id),
    )
    done_count = sum(1 for t in ctx.tasks if t.status in _DONE_TASK_STATUSES)
    open_blockers = [b for b in ctx.blockers if b.status == "open"]

    lines: list[str] = ["# Tasks", ""]

    lines.append(f"## Active ({len(active)})")
    if not active:
        lines.append("_No active tasks._")
    else:
        lines += [
            "| Title | Status | Priority |",
            "|---|---|---|",
        ]
        for t in active:
            priority = _sanitize(t.priority) or "—"
            lines.append(f"| {_trunc(t.title)} | {t.status} | {priority} |")

    lines += ["", f"## Done", f"{done_count} completed.", ""]

    lines.append("## Open blockers")
    if not open_blockers:
        lines.append("_No open blockers._")
    else:
        lines += [
            "| Title | Status |",
            "|---|",
        ]
        for b in open_blockers:
            lines.append(f"| {_trunc(b.title)} | {b.status} |")

    return lines


def _decisions_body(ctx: RenderContext) -> list[str]:
    # Sorted newest-first by created_at then id for stability.
    decisions = sorted(ctx.decisions, key=lambda d: (d.created_at, d.id), reverse=True)

    lines: list[str] = ["# Decisions", ""]
    lines.append("## Decision log")
    if not decisions:
        lines.append("_No decisions recorded yet._")
    else:
        lines += [
            "| Status | Title | Decision |",
            "|---|---|---|",
        ]
        for d in decisions:
            lines.append(
                f"| {d.status} | {_trunc(d.title, 50)} | {_trunc(d.decision, 80)} |"
            )

    return lines


def _risks_body(ctx: RenderContext) -> list[str]:
    open_risks = [
        r for r in ctx.risks if r.status not in _CLOSED_RISK_STATUSES
    ]
    closed_risks = [r for r in ctx.risks if r.status in _CLOSED_RISK_STATUSES]
    open_risks.sort(key=lambda r: (_SEVERITY_ORDER.get(r.severity, 99), r.id))
    open_blockers = [b for b in ctx.blockers if b.status == "open"]

    lines: list[str] = ["# Risks", ""]

    lines.append("## Open risks")
    if not open_risks:
        lines.append("_None yet._")
    else:
        lines += [
            "| Severity | Title | Status | Mitigation |",
            "|---|---|---|---|",
        ]
        for r in open_risks:
            mitigation = _trunc(r.mitigation, 60) if r.mitigation else "—"
            lines.append(
                f"| {r.severity} | {_trunc(r.title, 50)} | {r.status} | {mitigation} |"
            )

    lines += ["", f"## Closed risks", f"{len(closed_risks)} closed.", ""]

    lines.append("## Open blockers")
    if not open_blockers:
        lines.append("_No open blockers._")
    else:
        lines += [
            "| Title | Status |",
            "|---|---|",
        ]
        for b in open_blockers:
            lines.append(f"| {_trunc(b.title)} | {b.status} |")

    return lines


# --- operational layer ----------------------------------------------------


def _agents_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Agent rules (cross-tool alias)",
        "",
        "Cross-tool alias of [AGENT_RULES.md](AGENT_RULES.md). Codex, Cursor, and",
        "OpenCode read this file; the canonical rules live in AGENT_RULES.md.",
        "",
        "See [AGENT_RULES.md](AGENT_RULES.md).",
    ]


def _agent_rules_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Agent rules",
        "",
        "## Scope",
        "- Operate only within [FILES_ALLOWED.md](FILES_ALLOWED.md).",
        "- Never read, modify, or exfiltrate paths in"
        " [FILES_FORBIDDEN.md](FILES_FORBIDDEN.md).",
        "",
        "## Approval",
        "- Every write proposed through an external AI surface is approval-gated"
        " (proposal -> human approve -> apply).",
        "- Local human actions may write directly; they are still validated and"
        " audited.",
        "",
        "## Response format",
        "1. What changed",
        "2. Files touched",
        "3. Validation performed",
        "4. Risks / open questions",
        "5. Exact next step",
    ]


def _files_allowed_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Allowed paths",
        "",
        "Glob allow-list of paths agents may read or modify for this project.",
        "Forbidden paths always win over allowed.",
        "",
        "- (none configured yet)",
    ]


def _files_forbidden_body(_ctx: RenderContext) -> list[str]:
    globs = sorted(
        [
            ".env",
            ".env.*",
            "**/.env",
            "**/.env.*",
            "secrets/**",
            "**/secrets/**",
            "credentials/**",
            "**/*credential*",
            "**/*.pem",
            "**/*.key",
        ]
    )
    return [
        "# Forbidden paths",
        "",
        "Glob deny-list of paths agents must never read, modify, or exfiltrate.",
        "These win over any allow rule and are never removed once added.",
        "",
        *[f"- {g}" for g in globs],
    ]


def _architecture_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Architecture",
        "",
        "## Stack",
        "_Not yet documented._",
        "",
        "## Module map",
        "_Not yet documented._",
        "",
        "## Key constraints",
        "- See [AGENT_RULES.md](AGENT_RULES.md).",
        "- Depth lives under `docs/`, not inlined here.",
    ]


def _test_plan_body(_ctx: RenderContext) -> list[str]:
    return [
        "# Test plan",
        "",
        '## What "verified" means',
        "_Not yet documented for this project._",
        "",
        "## Commands",
        "- (none configured yet)",
        "",
        "## Smoke steps",
        "- (none configured yet)",
    ]


def _prompts_body(_ctx: RenderContext) -> list[str]:
    families = sorted(["claude", "codex", "chatgpt", "opencode", "cursor", "shared"])
    return [
        "# Prompts",
        "",
        "Index of ready-to-paste prompt templates. The prompts live in files under",
        "`prompts/<agent>/`, not inlined here.",
        "",
        *[f"- prompts/{family}/" for family in families],
    ]


def _changelog_body(ctx: RenderContext) -> list[str]:
    # Date derives from project.created_at (stable), never wall-clock.
    created_date = ctx.project.created_at[:10]
    return [
        "# Changelog",
        "",
        "Reverse-chronological, human-readable change history.",
        "",
        f"- {created_date}: Project folder initialised by Planarus.",
    ]


BODY_RENDERERS: dict[str, Callable[[RenderContext], list[str]]] = {
    "PROJECT.md": _project_body,
    "CONTEXT.md": _context_body,
    "STATUS.md": _status_body,
    "NEXT_STEP.md": _next_step_body,
    "ROADMAP.md": _roadmap_body,
    "TASKS.md": _tasks_body,
    "DECISIONS.md": _decisions_body,
    "RISKS.md": _risks_body,
    "AGENTS.md": _agents_body,
    "AGENT_RULES.md": _agent_rules_body,
    "FILES_ALLOWED.md": _files_allowed_body,
    "FILES_FORBIDDEN.md": _files_forbidden_body,
    "ARCHITECTURE.md": _architecture_body,
    "TEST_PLAN.md": _test_plan_body,
    "PROMPTS.md": _prompts_body,
    "CHANGELOG.md": _changelog_body,
}


def render(spec: ContextFileSpec, ctx: RenderContext) -> str:
    """Render the full file text (front matter + body) for one spec."""
    body = BODY_RENDERERS[spec.filename](ctx)
    return _wrap(spec.kind, ctx, body)
